name: aura1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, use an assets section:
  assets:
  
    - assets/images/bracelets.jpg
    - assets/images/g4.jpg
    - assets/images/gems1.jpg
    - assets/images/green ear.jpg
    - assets/images/making gold.webp
    - assets/images/ring3.webp
    - assets/images/b1.webp
    - assets/images/b2.webp
    - assets/images/n1.webp
    - assets/images/n2.webp
    - assets/images/n3.webp
    - assets/images/r1.webp
    - assets/images/r2.webp
    - assets/images/map.png





  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/R1.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
